import turtle as t
t.bgcolor("light green")
t.speed(15)
def a():
    t.shape("turtle")
    t.penup()
    t.goto(350,1000)
    t.pendown()
    t.color("red")
    t.begin_fill()
    for i in range(4):
        t.fd(100)
        t.right(90)
    t.end_fill()
def b():
    t.shape("turtle")
    t.penup()
    t.goto(-400,1000)
    t.pendown()
    t.color("red")
    t.begin_fill()
    for i in range(4):
        t.fd(100)
        t.right(90)
    t.end_fill()
def c():
    t.shape("turtle")
    t.penup()
    t.goto(-400,-1000)
    t.pendown()
    t.color("red")
    t.begin_fill()
    for i in range(4):
        t.fd(100)
        t.right(90)
    t.end_fill()
def d():
    t.shape("turtle")
    t.penup()
    t.goto(350,-1000)
    t.pendown()
    t.color("red")
    t.begin_fill()
    for i in range(4):
        t.fd(100)
        t.right(90)
    t.end_fill()

def e():
    t.penup()
    t.goto(-20,1000)
    t.pendown()
    t.color("red")
    t.begin_fill()
    for i in range(4):
        t.fd(100)
        t.right(90)
    t.end_fill()
    
def f():
    t.penup()
    t.goto(-20,-1000)
    t.pendown()
    t.color("red")
    t.begin_fill()
    for i in range(4):
        t.fd(100)
        t.right(90)
    t.end_fill()

a()
b()
c()
d()
e()
f()

t.penup()
t.goto(0,0)
t.pendown()
t.color('yellow')
t.begin_fill()
t.penup()
t.goto(0,0)
t.pendown()
t.circle(100)
t.penup()
t.goto(0,0)
t.pendown()
t.circle(-100)
t.right(100)
t.penup()
t.goto(200,0)
t.pendown()
t.circle(-200)
t.penup()
t.goto(-200,0)
t.pendown()
t.circle(200)
t.end_fill()
t.hideturtle()
t.done()

    
